name: build

on:
  push:
    paths:
      - .gitmodules
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build job
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: build packages
        uses: zjuyk/pkgbuild-aur@master
        with:
          pkg-name: dosbox-staging
