name: build

on:
  push:
    paths:
      - .gitmodules
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build job
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: build packages
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: pkgbuild
          pkgname: dosbox-staging
